import { Biodata } from './type';

export const sampleBiodata: Biodata = {
  id: 'sample-biodata',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  settings: {
    background: "../../../public/images/template-previews/temp1.jpg",
    idolImage: '/images/om-symbol.png',
    tagline: 'Seeking a life partner who values tradition and culture',
    fontFamily: 'Geist',
    primaryColor: '#000',
    shareEnabled: true,
    privacySettings: {
      showContactDetails: true,
      showEmail: true,
      showAddress: true,
      showIncome: false,
    },
    displayPreferences: ['partner_preferences'],
  },
  personalInformation: {
    fullName: 'Rahul Sharma',
    dateOfBirth: '10/04/1992',
    timeOfBirth: '11:15 AM',
    placeOfBirth: 'Delhi, India',
    age: 31,
    height: '5\' 10"',
    weight: '75 kg',
    bloodGroup: 'B+',
    maritalStatus: 'Never Married',
    religion: 'Hindu',
    caste: 'Brahmin',
    subCaste: 'Sharma',
    gothra: 'Kashyap',
    rashi: 'Mithun',
    nakshatra: 'Ardra',
    manglik: 'No',
    education: 'B.Tech in Computer Science',
    profession: 'Software Engineer',
    annualIncome: '12-15 LPA',
    hobbies: ['Reading', 'Travelling', 'Photography'],
    languages: ['Hindi', 'English', 'Sanskrit'],
    diet: 'Vegetarian',
    aboutMe:
      'I am a software engineer working with a multinational company. I value family traditions and am looking for a life partner who shares similar values. I enjoy reading books in my free time and love to travel and explore new places.',
  },
  familyInformation: {
    // fatherName: 'Mukesh Sharma',
    // fatherOccupation: 'Retired Government Officer',
    // motherName: 'Neeta Sharma',
    // motherOccupation: 'Homemaker',
    // brothers: 1,
    // brothersMarried: 1,
    // sisters: 0,
    // sistersMarried: 0,
    familyType: 'Nuclear',
    familyValues: 'Traditional',
    familyStatus: 'Upper Middle Class',
    familyBackground:
      'Originally from Jaipur, settled in Delhi for the last 30 years.',
    aboutFamily:
      'We are a small, close-knit family with traditional values. My father retired as a senior government official, and my mother is a homemaker. My elder brother is married and works as a doctor in the USA.',
    nativePlace: 'Jaipur, Rajasthan',
    // siblings: [
    //   {
    //     name: 'Dr. Amit Sharma',
    //     occupation: 'Medical Doctor',
    //     education: 'MBBS, MD',
    //     age: 35,
    //   },
    // ],
    customMembers: [
      {
        id: 'custom_1',
        relation: 'Grandfather',
        details: 'Shri Ramesh Sharma \n 0 years \n, Retired Principal',
      },
      {
        id: 'custom_2',
        relation: 'Nana-Nani',
        details: 'Shri Ramesh Sharma \n, 80 years,\n Retired Principal',
      },
      {
        id: 'custom_3',
        relation: 'Dadaji & Dadiji',
        details: 'Shri Ramesh Sharma \n, 80 years \n, Retired Principal',
      },
      {
        id: 'custom_4',
        relation: 'Papaji & Mummyji',
        details: 'Shri Ramesh Sharma\n, 80 years,\n Retired Principal',
      },
      {
        id: 'custom_5',
        relation: 'Tauji & Tai',
        details: 'Shri Ramesh Sharma,\n 80 years\n, Retired Principal',
      },
    ],
  },
  contactInformation: {
    mobileNumber: '+91 98765 43210',
    alternateNumber: '+91 87654 32109',
    email: 'rahul.sharma@example.com',
    address: '123, Green Park Extension',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110016',
  },
  partnerPreferences: {
    ageRange: '25-29 years',
    heightRange: '5\'2" - 5\'7"',
    education: ['Graduate', 'Post Graduate'],
    profession: ['Teacher', 'Doctor', 'Engineer', 'Government Service'],
    incomeRange: 'Not a criteria',
    religion: 'Hindu',
    caste: ['Brahmin', 'Baniya'],
    maritalStatus: ['Never Married'],
    location: ['Delhi NCR', 'Jaipur'],
    additionalPreferences:
      'Looking for a well-educated girl who values Indian traditions and culture. She should be understanding, supportive, and family-oriented.',
  },
  additionalPhotos: ['/images/sample-profile.jpg'],
  horoscope: {
    url: '/documents/sample-horoscope.pdf',
    showInBiodata: true,
  },
} 