export const fontOptions = [
  { label: 'Arial', value: 'Arial, sans-serif' },
  { label: 'Verdana', value: 'Verdana, sans-serif' },
  { label: 'Helvetica', value: 'Helvetica, sans-serif' },
  { label: 'Tahoma', value: 'Tahoma, sans-serif' },
  { label: 'Trebuchet MS', value: '"Trebuchet MS", sans-serif' },
  { label: 'Times New Roman', value: '"Times New Roman", serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Garamond', value: 'Garamond, serif' },
  { label: 'Courier New', value: '"Courier New", monospace' },
  { label: 'Lucida Console', value: '"Lucida Console", monospace' },
  { label: 'Roboto', value: 'Roboto, sans-serif' },
  { label: 'Open Sans', value: '"Open Sans", sans-serif' },
  { label: 'Lato', value: 'Lato, sans-serif' },
  { label: 'Montserrat', value: 'Montserrat, sans-serif' },
  { label: 'Poppins', value: 'Poppins, sans-serif' },
  { label: 'Nunito', value: 'Nunito, sans-serif' },
  { label: 'Merriweather', value: 'Merriweather, serif' },
  { label: 'Playfair Display', value: '"Playfair Display", serif' },
  { label: 'Ubuntu', value: 'Ubuntu, sans-serif' },
  { label: 'Raleway', value: 'Raleway, sans-serif' },
  { label: 'Quicksand', value: 'Quicksand, sans-serif' },
  { label: 'Work Sans', value: '"Work Sans", sans-serif' },
  { label: 'Source Sans Pro', value: '"Source Sans Pro", sans-serif' },
  { label: 'PT Sans', value: '"PT Sans", sans-serif' },
  { label: 'PT Serif', value: '"PT Serif", serif' },
  { label: 'Oswald', value: 'Oswald, sans-serif' },
  { label: 'Josefin Sans', value: '"Josefin Sans", sans-serif' },
  { label: 'DM Sans', value: '"DM Sans", sans-serif' },
  { label: 'Bitter', value: 'Bitter, serif' },
  { label: 'Fira Sans', value: '"Fira Sans", sans-serif' },
  { label: 'Inconsolata', value: 'Inconsolata, monospace' },
  { label: 'Mukta', value: 'Mukta, sans-serif' },
  { label: 'Exo 2', value: '"Exo 2", sans-serif' },
  { label: 'Hind', value: 'Hind, sans-serif' },
  { label: 'Cabin', value: 'Cabin, sans-serif' },
  { label: 'Overpass', value: 'Overpass, sans-serif' },
  { label: 'Titillium Web', value: '"Titillium Web", sans-serif' },
  { label: 'Oxygen', value: 'Oxygen, sans-serif' },
  { label: 'Muli', value: 'Muli, sans-serif' },
  { label: 'Zilla Slab', value: '"Zilla Slab", serif' },
  { label: 'Arvo', value: 'Arvo, serif' },
  { label: 'Varela Round', value: '"Varela Round", sans-serif' },
  { label: 'Karla', value: 'Karla, sans-serif' },
  { label: 'IBM Plex Sans', value: '"IBM Plex Sans", sans-serif' },
  { label: 'Manrope', value: 'Manrope, sans-serif' },
  { label: 'Barlow', value: 'Barlow, sans-serif' },
  { label: 'Rubik', value: 'Rubik, sans-serif' },
  { label: 'Anton', value: 'Anton, sans-serif' },
  { label: 'Dosis', value: 'Dosis, sans-serif' },
  { label: 'Signika', value: 'Signika, sans-serif' },
  { label: 'Tajawal', value: 'Tajawal, sans-serif' },
]
